###
GET http://localhost:3004/job/get-jobs/f


###
GET http://localhost:3004/job/get-company-jobs/cmp-12hahas23


###
GET http://localhost:3004/job/get-jobs


###
GET  http://localhost:3004/job/get-all-applications/cmp-ZZc9384EQl


###
POST http://localhost:3004/job/create-job
Content-Type: application/json

//"cmp-12hahas23"
{
    "company_id":"cmp-12hadas23",
    "jobData":{"role":"Devops Engineer"}
}


###
POST http://localhost:3004/job/test
Content-Type: application/json

{
    "key":"JOB_POST",
    "data":"back end developer"
}


###
POST http://localhost:3004/job/reject
Content-Type: application/json

{
    "job_id" : "6677c5d2e333220c8bed921b",
    "user_id": "_EDxD8v1JrMWz_K00AjS"
}